global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  
  - job_name: mysql
    static_configs:
      - targets:
        - '192.168.10.2:9104'
  
  - job_name: apache
    static_configs:
      - targets:
        - '192.168.10.4:9117'
  
  - job_name: dnsmasq
    static_configs:
      - targets:
        - '192.168.10.3:9153'
  
  - job_name: node_exporter
    static_configs:
      - targets:
        - '192.168.10.2:9100'
        - '192.168.10.3:9100'
        - '192.168.10.4:9100'
