# -----------------------
#       Prometheus
# -----------------------
prometheus_targets:
  node:
    - targets:
      - 192.168.10.2:9100
      - 192.168.10.3:9100
      - 192.168.10.4:9100
      - 192.168.10.5:9100
      labels:
        env: JFNP

prometheus_scrap_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ inventory_hostname }}:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "/etc/prometheus/file_sd/node.yml"


# -----------------------
#       Grafana
# -----------------------

# Creates a Grafana Administrator user 'Admin' for installation Grafana
grafana_security:
  admin_user: admin 
  admin_password: admin 

# Configure Grafana datasource
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://192.168.10.5:9090'
    basicAuth: false

# grafana_dashboards:
#     # Dashboard voor SQL
#   - dashboard_id: '7362'
#     revision_id: '1'
#     datasource: prometheus

  

  