{
 "title": "Dnsmasq ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Queries Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dnsmasq_servers_queries_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cachesize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "dnsmasq_cachesize", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "dnsmasq_servers_queries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "dnsmasq_misses", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "dnsmasq_leases", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "dnsmasq_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Insertions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "dnsmasq_insertions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "dnsmasq_auth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Build info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 32 },
   "targets": [
    { "expr": "apache_exporter_build_info", "legendFormat": "__auto" }
   ]
  }
 ]
}